/** Environment fallback: when a reached scene resolves no exact shot art, show the empty-room master for
 * where the scene takes place. Masters contain no identifiable character and no state-specific prop, so they
 * can never reveal a later outfit, identity or custody state early (owner decision: every page has fitting art).
 * Scenes with no suitable master return undefined and stay text-only until new art exists. */
import type { GameState } from '../state/schema';
import { helix4 } from '../content/chapter4-case';

type Master = { assetId: string; alt: string };
const masters = {
  apartment: { assetId: 'opening-apartment-master-v3-production', alt: 'Adrian’s apartment: rain on the tall window, the lamp lit by the counter, no one in the room.' },
  apartmentDay: { assetId: 'c5-s01-daytime-apartment-anchor-v5-noir-production', alt: 'The apartment sofa and low table on an overcast afternoon, the lights off.' },
  apartmentNight: { assetId: 'c5-people-night-apartment-master-v1-noir-production', alt: 'The apartment at night, the window dark and the lamp lit, no one in the room.' },
  phone: { assetId: 'chapter3-surveillance-phone-v1-lift-production', alt: 'The monitored phone lies lit on the apartment table; its screen is unreadable.' },
  wardrobe: { assetId: 'eve-bg-wardrobe-continuity-noir-v2-lift-production', alt: 'A dressing area: a suit, a gown and a dress on the rail beside a lit vanity mirror.' },
  car: { assetId: 'car-rain-window-noir-v2-lift-production', alt: 'Rain beads across the car window as the city passes in the blue light.' },
  securityLobby: { assetId: 'axiom-security-lobby-v2-production', alt: 'The Axiom security lobby: scanning lanes and glass gates under cold light.' },
  executiveOffice: { assetId: 'eve-bg-sloane-office-continuity-noir-v2-lift-production', alt: 'An empty executive office high above the city, the desk facing the windows.' },
  glassLobby: { assetId: 'eve-bg-glass-lobby-noir-v2-lift-production', alt: 'The Glass House elevator lobby at night: dark marble, one warm sconce and closed elevator doors.' },
  shoppingStreet: { assetId: 'c5-s02-shopping-street-master-v1-noir-production', alt: 'A quiet shopping street with a lit shop window.' },
  publicRecords: { assetId: 'chapter4-public-records-noir-v2-production', alt: 'The public records reading room: long tables, a folder and a registration form.' },
  closedReport: { assetId: 'chapter4-interest-closed-report-v1-production', alt: 'The closed report lies on the table after the session.' },
  privateDinner: { assetId: 'chapter4-private-time-dinner-v1-lift-production', alt: 'An apartment table set for dinner, no one yet seated.' },
  rooftop: { assetId: 'harbour-rooftop-terrace-noir-v1-production', alt: 'The Harbour roof terrace at night: chairs, the parapet light and the towers beyond.' },
  hotelRoom: { assetId: 'harbour-hotel-room-noir-v1-production', alt: 'A small hotel room near the harbour, one lamp lit.' },
  noodleCounter: { assetId: 'noodle-counter-noir-v1-production', alt: 'The late noodle counter near Compliance, the stools empty.' },
  serviceGallery: { assetId: 'glass-house-service-gallery-noir-v1-production', alt: 'The Glass House service gallery, empty.' },
  elevator: { assetId: 'descending-elevator-noir-v1-production', alt: 'The inside of a descending elevator, empty.' },
  garage: { assetId: 'service-garage-noir-v1-production', alt: 'The service garage below the Glass House, empty.' },
  officeDusk: { assetId: 'si-office-dusk-noir-v1-production', alt: 'The Strategic Intelligence office at dusk, empty.' },
  axiomGates: { assetId: 'axiom-gates-noir-v1-production', alt: 'Outside the Axiom gates, empty, in the rain.' },
  lantern: { assetId: 'lantern-exterior-noir-v1-production', alt: 'Outside the Lantern, empty, the windows lit.' },
  helixSuite: { assetId: 'helix-exec-suite-noir-v2-production', alt: 'The Helix executive suite, empty: a long desk, city light and closed doors.' },
  helixReception: { assetId: 'helix-small-reception-noir-v2-lift-production', alt: 'Outside the smaller Helix reception, empty.' },
  clinicalRecords: { assetId: 'clinical-records-room-noir-v2-lift-production', alt: 'The clinical records room, empty: files, a reading table and a lamp.' },
  reviewRoom: { assetId: 'ch4-review-room-noir-v2-lift-production', alt: 'The Helix review room, empty: a long table set for an authorized session.' },
  asterProof: { assetId: 'aster-proof-table-noir-v2-lift-production', alt: 'The Aster studio proof table, empty.' },
  harbourRoom: { assetId: 'harbour-room-noir-v2-lift-production', alt: 'The Harbour room, empty, the works along the wall.' },
  consultation: { assetId: 'clinic-consultation-suite-noir-v2-lift-production', alt: 'The clinic consultation suite, empty.' },
  recordsCounter: { assetId: 'chapter4-outside-public-counter-noir-v2-lift-production', alt: 'The public records counter, empty, a copy-request tray on the ledge.' },
  publicDesk: { assetId: 'chapter4-favor-public-desk-noir-v2-lift-production', alt: 'A reserved desk in the public records office, empty.' },
  helixWorkroom: { assetId: 'chapter4-favor-julian-workroom-noir-v2-lift-production', alt: 'A Helix workroom booked for the afternoon, empty.' },
} satisfies Record<string, Master>;
type Key = keyof typeof masters;

/** Node → master. Only nodes whose authored place matches the master's location are listed. */
const byNode: Record<string, Key> = {
  // Opening day, before the clinic.
  'apartment.departure': 'apartment',
  'release.departure': 'executiveOffice',
  'release.home': 'apartment',
  'evening.plan': 'apartment',
  'evening.home': 'apartment',
  'warning.first': 'apartment',
  'warning.second': 'apartment',
  'warning.third': 'apartment',
  'dayend.accepted': 'apartment',
  // Clinic day.
  'clinic.morning': 'apartment',
  'clinic.contact': 'apartment',
  'clinic.morningReply': 'apartment',
  'clinic.travel': 'car',
  'clinic.entrance': 'securityLobby',
  'clinic.screened': 'securityLobby',
  'clinic.departure': 'securityLobby',
  'clinic.complete': 'car',
  // Consultation suite (partial states fall back only where no exact frame resolves).
  'clinic.profileReview': 'consultation',
  'clinic.voice': 'consultation',
  'clinic.voiceReply': 'consultation',
  'clinic.stopConfirm': 'consultation',
  'clinic.stopped': 'consultation',
  'clinic.examResult': 'consultation',
  'clinic.makeup': 'consultation',
  // Glass House evening.
  'mission.home': 'apartmentNight',
  'mission.homePresentation': 'apartmentNight',
  'mission.homeContact': 'apartmentNight',
  'mission.elevator': 'glassLobby',
  'mission.entry': 'glassLobby',
  'mission.hub': 'glassLobby',
  'mission.marcus': 'glassLobby',
  'mission.marcusReply': 'glassLobby',
  'mission.celeste': 'glassLobby',
  'mission.celesteReply': 'glassLobby',
  'mission.cover': 'glassLobby',
  'mission.leadReview': 'glassLobby',
  'mission.leadResult': 'glassLobby',
  'mission.leadRead': 'glassLobby',
  'mission.assessmentReview': 'glassLobby',
  'mission.escape': 'glassLobby',
  'mission.exchange': 'serviceGallery',
  'mission.confrontation': 'serviceGallery',
  'mission.debrief': 'elevator',
  'mission.debriefReply': 'elevator',
  'mission.warning1': 'elevator',
  'mission.warning2': 'elevator',
  'mission.warning3': 'elevator',
  'mission.garage': 'garage',
  'mission.complete': 'garage',
  // Opening day, the three formerly blank endings.
  'dayend.cautious': 'officeDusk',
  'dayend.walkaway': 'axiomGates',
  'evening.goodbye': 'lantern',
  // Chapter 3.
  'chapter3.home': 'apartment',
  'chapter3.complete': 'apartment',
  'chapter3.mayaContact': 'apartment',
  'chapter3.mayaTalk': 'phone',
  'chapter3.mayaClose': 'phone',
  'chapter3.pressure': 'phone',
  'chapter3.rest': 'apartment',
  'chapter3.nightComplete': 'apartment',
  'chapter3.morningPlan': 'apartment',
  'chapter3.voss': 'phone',
  'chapter3.vossPlan': 'phone',
  'chapter3.rook': 'phone',
  'chapter3.rookCompare': 'phone',
  'chapter3.rookReply': 'phone',
  'chapter3.informationEnd': 'phone',
  'chapter3.invitation': 'phone',
  'chapter3.verifyOffer': 'phone',
  'chapter3.opportunityEnd': 'phone',
  'chapter3.truths': 'apartment',
  'chapter3.disclosure': 'phone',
  'chapter3.calendar': 'phone',
  'chapter3.departure': 'apartment',
  'chapter3.executive': 'helixSuite',
  'chapter3.executiveWork': 'helixSuite',
  'chapter3.marcusRecord': 'helixSuite',
  'chapter3.marcusLeverage': 'helixSuite',
  'chapter3.reception': 'helixReception',
  'chapter3.institutional': 'clinicalRecords',
  'chapter3.reviewQualification': 'clinicalRecords',
  // Chapter 4 (review scenes and the favor branch on the client; see below).
  'chapter4.outside': 'recordsCounter',
  'chapter4.power': 'recordsCounter',
  'chapter4.notice': 'phone',
  'chapter4.interest': 'closedReport',
  'chapter4.intimacy': 'privateDinner',
  // Chapter 5.
  'chapter5.home': 'apartmentDay',
  'chapter5.presentation': 'wardrobe',
  'chapter5.infrastructure': 'apartmentDay',
  'chapter5.invitation': 'apartmentDay',
  'chapter5.offer': 'apartmentDay',
  'chapter5.terms': 'apartmentDay',
  'chapter5.spend': 'shoppingStreet',
  'chapter5.proof': 'asterProof',
  'chapter5.room': 'harbourRoom',
  'chapter5.salon': 'rooftop',
  'chapter5.salon-room': 'hotelRoom',
  'chapter5.people': 'apartmentNight',
  'chapter5.want': 'apartmentNight',
  'chapter5.return': 'apartmentNight',
  'chapter5.complete': 'apartmentNight',
  // Chapter 6 (friction only while the Counter is not running; see below).
  'chapter6.benefit': 'apartmentDay',
  'chapter6.expectation': 'phone',
  'chapter6.exit': 'apartmentNight',
  'chapter6.proof': 'phone',
  'chapter6.counterpower': 'apartmentNight',
  'chapter6.resolve': 'apartmentNight',
  'chapter6.complete': 'apartmentNight',
  // Chapter 7.
  'chapter7.confirm': 'apartmentDay',
  'chapter7.standing': 'apartmentDay',
  'chapter7.held': 'recordsCounter',
  'chapter7.street': 'shoppingStreet',
  'chapter7.lift': 'elevator',
  'chapter7.wardrobe': 'wardrobe',
  'chapter7.grey': 'shoppingStreet',
  'chapter7.pursue': 'publicRecords',
  'chapter7.close': 'apartmentNight',
  'chapter7.effects': 'apartmentNight',
  'chapter7.night': 'apartmentNight',
  'chapter7.complete': 'apartmentNight',
  // The Predator road: Marcus's car, his floor, and her own office two floors down.
  'chapter7.summons': 'car',
  // The Executive road: The Room.
  'chapter7.table': 'privateDinner',
  'chapter7.fortyone': 'helixSuite',
  'chapter7.contract': 'helixSuite',
  'chapter7.hallway': 'helixReception',
  'chapter7.key': 'helixWorkroom',
  'chapter7.tonight': 'apartmentNight',
  // The Institutional road: Level 71.
  'chapter7.gate': 'securityLobby',
  'chapter7.window': 'executiveOffice',
  'chapter7.scope': 'executiveOffice',
  // The Outside road: The Sender.
  'chapter7.flit': 'apartmentDay',
  'chapter7.room': 'apartmentNight',
  'chapter7.rules': 'apartmentNight',
  'chapter7.page': 'apartmentNight',
  'chapter7.price': 'apartmentNight',
  'chapter7.dusk': 'rooftop',
  'chapter7.crossing': 'officeDusk',
  'chapter7.desk': 'officeDusk',
  'chapter7.watched': 'apartmentNight',
  'chapter7.office': 'helixSuite',
  'chapter7.terms': 'helixSuite',
  'chapter7.corridor': 'helixReception',
  'chapter7.floor': 'helixWorkroom',
  'chapter7.evening': 'apartmentNight',
  // Chapter 8 (the Helix room on the executive road is on EVE Art's gap list; advance keeps the apartment).
  'chapter8.cost': 'apartmentDay',
  'chapter8.work': 'shoppingStreet',
  'chapter8.maintenance': 'apartmentDay',
  'chapter8.fireescape': 'apartmentDay',
  'chapter8.leverage': 'phone',
  'chapter8.advance': 'apartmentNight',
  'chapter8.emerald': 'shoppingStreet',
  'chapter8.wake': 'lantern',
  'chapter8.number14': 'apartmentNight',
  'chapter8.close': 'apartmentNight',
  'chapter8.call': 'phone',
  'chapter8.complete': 'apartmentNight',
  // The Predator road: three weeks on the Helix floors.
  'chapter8.weeks': 'helixWorkroom',
  'chapter8.hub': 'helixWorkroom',
  'chapter8.friday': 'helixSuite',
  'chapter8.julian': 'helixReception',
  'chapter8.evening': 'helixWorkroom',
  // The Executive road: The Terms.
  'chapter8.orbit': 'helixWorkroom',
  'chapter8.favours': 'helixWorkroom',
  'chapter8.dinner': 'privateDinner',
  'chapter8.tray': 'helixSuite',
  'chapter8.late': 'apartmentNight',
  // The Institutional road: Scope.
  // The Outside road: Provenance.
  'chapter8.settle': 'apartmentNight',
  'chapter8.leads': 'apartmentNight',
  'chapter8.plant': 'apartmentNight',
  'chapter8.terminal': 'glassLobby',
  'chapter8.after': 'rooftop',
  'chapter8.rota': 'officeDusk',
  'chapter8.tasked': 'officeDusk',
  'chapter8.records': 'clinicalRecords',
  'chapter8.backseat': 'car',
  'chapter8.afterhours': 'apartmentNight',
  // Chapter 9 (the shared bridge).
  'chapter9.arrive': 'apartmentDay',
  'chapter9.names': 'shoppingStreet',
  'chapter9.table': 'privateDinner',
  'chapter9.auction': 'harbourRoom',
  'chapter9.assemble': 'phone',
  'chapter9.resolve': 'apartmentNight',
  'chapter9.cafe': 'shoppingStreet',
  'chapter9.river': 'shoppingStreet',
  'chapter9.archive': 'publicRecords',
  'chapter9.counsel': 'publicRecords',
  'chapter9.complete': 'apartmentNight',
  // Chapter 10 (stand-ins until EVE Art's Chapter 10 frames: the Lindqvist, the wall, the archive).
  'chapter10.breakfast': 'privateDinner',
  'chapter10.claimed': 'phone',
  'chapter10.wall': 'apartmentNight',
  'chapter10.order': 'phone',
  'chapter10.answer': 'apartmentDay',
  'chapter10.invitation': 'apartmentNight',
  'chapter10.complete': 'apartmentNight',
  // The Predator road: Let Me Help (the Lindqvist from the shared spine, and the Helix floor).
  'chapter10.ask': 'helixWorkroom',
  'chapter10.table': 'privateDinner',
  'chapter10.offer': 'privateDinner',
  'chapter10.floor': 'helixWorkroom',
  'chapter10.evening': 'apartmentNight',
  'chapter10.ledger': 'apartmentNight',
  // The Executive road: A Lovely Man.
  'chapter10.orchid': 'helixWorkroom',
  'chapter10.lindqvist': 'privateDinner',
  'chapter10.calendar': 'privateDinner',
  'chapter10.paper': 'helixWorkroom',
  'chapter10.week': 'helixSuite',
  'chapter10.night': 'apartmentNight',
  // The Institutional road: A Very Good Officer.
  'chapter10.card': 'officeDusk',
  'chapter10.club': 'privateDinner',
  'chapter10.log': 'privateDinner',
  'chapter10.pages': 'officeDusk',
  'chapter10.fridays': 'executiveOffice',
  'chapter10.nightfall': 'apartmentNight',
  // Chapter 11 (stand-ins until EVE Art's Vesper frames: the black-glass front, the empty frames, the catalogue).
  'chapter11.arrival': 'glassLobby',
  'chapter11.viewing': 'harbourRoom',
  'chapter11.upstairs': 'serviceGallery',
  'chapter11.order': 'rooftop',
  'chapter11.ending': 'serviceGallery',
  'chapter11.after': 'apartmentNight',
  'chapter11.complete': 'apartmentNight',
  // The Predator road: The Catalogue (the shared Vesper set, from the client side).
  'chapter11.dress': 'apartmentNight',
  'chapter11.longroom': 'harbourRoom',
  'chapter11.book': 'privateDinner',
  'chapter11.powder': 'serviceGallery',
  'chapter11.terrace': 'rooftop',
  'chapter11.cloak': 'serviceGallery',
  'chapter11.late': 'car',
  'chapter11.ledger': 'apartmentNight',
  // The Executive road: The Good Pen (the shared Vesper set, on Julian's arm).
  'chapter11.frames': 'harbourRoom',
  'chapter11.pages': 'serviceGallery',
  'chapter11.pen': 'rooftop',
  'chapter11.signing': 'harbourRoom',
  // The Institutional road: The Receipt.
  'chapter11.threshold': 'harbourRoom',
  'chapter11.catalogue': 'harbourRoom',
  'chapter11.receipt': 'harbourRoom',
  'chapter11.countersign': 'harbourRoom',
  'chapter11.ride': 'car',
  'chapter11.drive': 'car',
  // Chapter 12 (stand-ins until EVE Art's Singapore frames: Changi, Emerald Hill, number 9, the Punkah Bar, the harbour).
  'chapter12.departure': 'apartmentNight',
  'chapter12.emerald': 'shoppingStreet',
  'chapter12.flat': 'wardrobe',
  'chapter12.straits': 'harbourRoom',
  'chapter12.sister': 'apartmentDay',
  'chapter12.night': 'rooftop',
  'chapter12.complete': 'car',
  // The Predator road: The Counterparty (stand-ins until EVE Art's Geneva frames: the bank, the lake, the Quai).
  'chapter12.geneva': 'hotelRoom',
  'chapter12.bank': 'reviewRoom',
  'chapter12.morel': 'privateDinner',
  'chapter12.vault': 'recordsCounter',
  'chapter12.lake': 'hotelRoom',
  'chapter12.call': 'phone',
  'chapter12.ledger': 'apartmentNight',
  // The Executive road: Whose Face (the shared Singapore set, with Julian beside her).
  'chapter12.changi': 'apartmentNight',
  'chapter12.tan': 'shoppingStreet',
  'chapter12.number9': 'wardrobe',
  'chapter12.punkah': 'harbourRoom',
  'chapter12.nora': 'apartmentDay',
  'chapter12.suite': 'hotelRoom',
  'chapter12.harbour': 'rooftop',
  // The Institutional road: Her City.
  'chapter12.wheels': 'glassLobby',
  'chapter12.landing': 'shoppingStreet',
  'chapter12.site': 'wardrobe',
  'chapter12.marlowe': 'harbourRoom',
  'chapter12.village': 'apartmentDay',
  'chapter12.report': 'hotelRoom',
  'chapter12.wall': 'rooftop',
  // Chapter 13 (stand-ins until EVE Art's frames: the reading room by day, the Claremont bar, a corridor and a door, never the room).
  'chapter13.brief': 'reviewRoom',
  'chapter13.week': 'apartmentNight',
  'chapter13.answer': 'apartmentNight',
  'chapter13.thursday': 'harbourRoom',
  'chapter13.after': 'car',
  'chapter13.morning': 'apartmentDay',
  'chapter13.complete': 'apartmentNight',
  // The Predator road: The Mirror.
  'chapter13.reading': 'reviewRoom',
  'chapter13.delphine': 'apartmentDay',
  'chapter13.midnight': 'apartmentNight',
  'chapter13.monitor': 'harbourRoom',
  'chapter13.late': 'apartmentNight',
  'chapter13.friday': 'apartmentDay',
  'chapter13.ledger': 'apartmentNight',
  // The Executive road: Held (the shared placement).
  'chapter13.placement': 'reviewRoom',
  'chapter13.days': 'helixWorkroom',
  'chapter13.wednesday': 'apartmentNight',
  'chapter13.claremont': 'harbourRoom',
  'chapter13.twoam': 'car',
  'chapter13.saturday': 'apartmentDay',
  // The Institutional road: Through Channels.
  'chapter13.tasking': 'officeDusk',
  'chapter13.dread': 'apartmentDay',
  'chapter13.channel': 'executiveOffice',
  'chapter13.reply': 'phone',
  'chapter13.corridor': 'hotelRoom',
  'chapter13.smallhours': 'apartmentNight',
  'chapter13.weekend': 'apartmentDay',
  // Chapter 14 (stand-ins until EVE Art's frames: Sloane under the wall, Maya's kitchen, the reading room, the fire escape).
  'chapter14.door': 'apartmentNight',
  'chapter14.order': 'apartmentDay',
  'chapter14.maya': 'apartmentDay',
  'chapter14.answer': 'apartmentNight',
  'chapter14.sunday': 'reviewRoom',
  'chapter14.after': 'rooftop',
  'chapter14.complete': 'apartmentNight',
  // The Predator road: Marcus Falls.
  'chapter14.dawn': 'apartmentNight',
  'chapter14.case': 'helixWorkroom',
  'chapter14.safe': 'apartmentNight',
  'chapter14.room': 'helixSuite',
  'chapter14.last': 'helixSuite',
  'chapter14.desk': 'helixSuite',
  'chapter14.evening': 'apartmentNight',
  'chapter14.ledger': 'apartmentNight',
  // The Executive road: The Signature.
  'chapter14.called': 'helixSuite',
  'chapter14.silence': 'car',
  'chapter14.truth': 'apartmentNight',
  'chapter14.ways': 'helixWorkroom',
  'chapter14.boardroom': 'helixSuite',
  'chapter14.night': 'apartmentNight',
  // The Institutional road: Officer of Record.
  'chapter14.notice': 'officeDusk',
  'chapter14.confession': 'executiveOffice',
  'chapter14.wire': 'phone',
  'chapter14.channels': 'reviewRoom',
  'chapter14.hearing': 'reviewRoom',
  'chapter14.dusk': 'apartmentNight',
  // Chapter 15 (stand-ins until EVE Art's frames: the wall on a wardrobe door, the Vesper at 2 a.m., the archive, the bridge).
  'chapter15.crew': 'apartmentNight',
  'chapter15.plan': 'apartmentDay',
  'chapter15.vesper': 'glassLobby',
  'chapter15.archive': 'serviceGallery',
  'chapter15.leash': 'officeDusk',
  'chapter15.phone': 'apartmentNight',
  'chapter15.complete': 'apartmentNight',
  // The Predator road: The Key (the shared Vesper archive, from the client side).
  'chapter15.gift': 'reviewRoom',
  'chapter15.people': 'apartmentNight',
  'chapter15.hour': 'serviceGallery',
  'chapter15.drawers': 'serviceGallery',
  'chapter15.week': 'apartmentDay',
  'chapter15.line': 'apartmentNight',
  'chapter15.ledger': 'apartmentNight',
  // The Executive road: By Appointment (the shared Vesper archive, by appointment).
  'chapter15.allies': 'apartmentNight',
  'chapter15.entry': 'glassLobby',
  'chapter15.stacks': 'serviceGallery',
  'chapter15.holds': 'officeDusk',
  'chapter15.last': 'apartmentNight',
  // The Institutional road: The Audit.
  'chapter15.warrant': 'executiveOffice',
  'chapter15.audit': 'harbourRoom',
  'chapter15.cabinets': 'clinicalRecords',
  'chapter15.aftermath': 'apartmentDay',
  'chapter15.eve': 'apartmentNight',
  // Chapter 16 (stand-ins until EVE Art's frames: cards on a floor at dawn, a clasp in a mirror, the embankment, the board table).
  'chapter16.dawn': 'apartmentNight',
  'chapter16.aim': 'apartmentDay',
  'chapter16.crew': 'apartmentDay',
  'chapter16.table': 'asterProof',
  'chapter16.dress': 'wardrobe',
  'chapter16.arrive': 'glassLobby',
  'chapter16.complete': 'harbourRoom',
  // The Predator road: The Seventh Chair.
  'chapter16.floor': 'apartmentNight',
  'chapter16.want': 'apartmentDay',
  'chapter16.beside': 'apartmentDay',
  'chapter16.order': 'apartmentDay',
  'chapter16.armour': 'wardrobe',
  'chapter16.door': 'glassLobby',
  'chapter16.layout': 'apartmentNight',
  'chapter16.purpose': 'apartmentDay',
  'chapter16.company': 'helixWorkroom',
  'chapter16.sequence': 'apartmentDay',
  'chapter16.clasp': 'apartmentNight',
  'chapter16.embankment': 'glassLobby',
  'chapter16.room': 'harbourRoom',
  // Chapter 17 (stand-ins until EVE Art's frames: the board table under the empty frames, three signatures, an orchid in a jug).
  'chapter17.opening': 'harbourRoom',
  'chapter17.defect': 'asterProof',
  'chapter17.sloane': 'harbourRoom',
  'chapter17.turn': 'harbourRoom',
  'chapter17.nell': 'harbourRoom',
  'chapter17.vote': 'harbourRoom',
  'chapter17.complete': 'rooftop',
  // The Predator road: Sit With Us (the long room reset for the board).
  'chapter17.sit': 'harbourRoom',
  'chapter17.market': 'harbourRoom',
  'chapter17.marcus': 'harbourRoom',
  'chapter17.offer': 'harbourRoom',
  'chapter17.eleanor': 'harbourRoom',
  'chapter17.hands': 'harbourRoom',
  'chapter17.minute': 'harbourRoom',
  // The Executive road: Collateral.
  'chapter17.product': 'harbourRoom',
  'chapter17.clause': 'harbourRoom',
  'chapter17.officer': 'harbourRoom',
  'chapter17.gift': 'harbourRoom',
  'chapter17.wall': 'harbourRoom',
  'chapter17.tally': 'harbourRoom',
  'chapter17.alone': 'harbourRoom',
  // Chapter 18 (stand-ins until EVE Art's frames: a newspaper, three envelopes and a match, a harbour wall, a window, one card).
  'chapter18.morning': 'apartmentDay',
  'chapter18.position': 'apartmentDay',
  'chapter18.people': 'noodleCounter',
  'chapter18.name': 'apartmentNight',
  'chapter18.later': 'rooftop',
  'chapter18.complete': 'apartmentNight',
  // The Predator road: Paid in Full.
  'chapter18.papers': 'apartmentDay',
  'chapter18.hold': 'harbourRoom',
  'chapter18.owes': 'apartmentNight',
  'chapter18.called': 'wardrobe',
  'chapter18.year': 'apartmentNight',
  'chapter18.last': 'apartmentNight',
  // The Executive road: Read Twice.
  'chapter18.friday': 'apartmentDay',
  'chapter18.settle': 'apartmentDay',
  'chapter18.keys': 'apartmentDay',
  'chapter18.dinner': 'apartmentNight',
  'chapter18.signed': 'wardrobe',
  'chapter18.page': 'apartmentNight',
  'chapter18.read': 'apartmentNight',
  // The Institutional road: Reasonable Notice, Fit for Purpose, No Further Action.
  'chapter16.briefing': 'apartmentNight',
  'chapter16.objective': 'apartmentDay',
  'chapter16.detail': 'apartmentDay',
  'chapter16.bundle': 'apartmentDay',
  'chapter16.uniform': 'apartmentNight',
  'chapter16.notice': 'glassLobby',
  'chapter17.exhibit': 'harbourRoom',
  'chapter17.warranty': 'harbourRoom',
  'chapter17.record': 'harbourRoom',
  'chapter17.leash': 'harbourRoom',
  'chapter17.harbour': 'harbourRoom',
  'chapter17.ruling': 'harbourRoom',
  'chapter17.aside': 'harbourRoom',
  'chapter18.debrief': 'executiveOffice',
  'chapter18.disposition': 'apartmentDay',
  'chapter18.light': 'apartmentDay',
  'chapter18.floor': 'executiveOffice',
  'chapter18.particulars': 'apartmentNight',
  'chapter18.scope': 'apartmentNight',
  'chapter18.nfa': 'wardrobe',
};

export function environmentShot(state: GameState): { shotId: string; assetId: string; alt: string } | undefined {
  const node = `${state.scene}.${state.phase}`;
  let key: Key | undefined = byNode[node];
  // Evening disclosure/closure away from the Lantern happen at home.
  if (!key && state.scene === 'evening' && ['disclosure', 'closure'].includes(state.phase) && state.day.evening !== 'meet')
    key = 'apartment';
  // Chapter 4 review scenes and the favor: the public records rooms, or Helix's on the Helix path.
  if (!key && state.scene === 'chapter4' && ['room', 'assessment', 'privateAccess', 'complete'].includes(state.phase))
    key = helix4(state) ? 'reviewRoom' : 'publicRecords';
  if (!key && node === 'chapter4.favor') key = helix4(state) ? 'helixWorkroom' : 'publicDesk';
  // Chapter 6 friction is at home, or at the noodle counter once the Counter is arranged.
  if (!key && node === 'chapter6.friction') key = state.choices['c6.counter-arranged'] ? 'noodleCounter' : 'apartmentNight';
  if (!key) return undefined;
  return { shotId: `environment.${key}`, ...masters[key] };
}

export const environmentMasterIds = Object.values(masters).map((m) => m.assetId);

/** Reached scenes with no suitable existing master: text-only until EVE Art supplies noir art.
 * Kept in one place so the audit test and the art handoff agree. */
export const environmentGaps = [
] as const;
