import { ChoiceSchema, speech, thought, paragraph, type Choice } from './schema';
const raw: Choice[] = [
  {
    id: 'bond.friend',
    node: 'apartment.bond',
    slot: 'bond',
    value: 'friend',
    label: 'She is my closest friend.',
    hint: 'The person I trust when professional caution stops being enough.',
    next: 'apartment.reply',
    response: [thought('Maya is the closest thing Adrian has to family inside Axiom.')],
  },
  {
    id: 'bond.love',
    node: 'apartment.bond',
    slot: 'bond',
    value: 'love',
    label: 'I love her. I have never said it.',
    hint: 'Adrian has protected the friendship by concealing something deeper.',
    next: 'apartment.reply',
    response: [
      thought('Adrian has spent years calling it friendship because friendship is safer.'),
    ],
  },
  {
    id: 'bond.colleague',
    node: 'apartment.bond',
    slot: 'bond',
    value: 'colleague',
    label: 'She is the colleague I trust most.',
    hint: 'Important, but the boundary remains professional.',
    next: 'apartment.reply',
    response: [
      thought(
        'Adrian trusts Maya with work that could end both careers, but not with everything else.',
      ),
    ],
  },
  {
    id: 'morning.yes',
    node: 'apartment.reply',
    slot: 'morning',
    value: 'yes',
    label: 'Absolutely.',
    hint: 'Send Maya a promise to see her tonight.',
    next: 'apartment.departure',
    response: [paragraph('Message sent: “Absolutely.”')],
  },
  {
    id: 'morning.work',
    node: 'apartment.reply',
    slot: 'morning',
    value: 'work',
    label: 'Probably working.',
    hint: 'Send the usual excuse.',
    next: 'apartment.departure',
    response: [paragraph('Message sent: “Probably working.”')],
  },
  {
    id: 'morning.day',
    node: 'apartment.reply',
    slot: 'morning',
    value: 'day',
    label: 'Depends how terrible my day is.',
    hint: 'Keep the invitation alive.',
    next: 'apartment.departure',
    response: [paragraph('Message sent: “Depends how terrible my day is.”')],
  },
  {
    id: 'morning.ignore',
    node: 'apartment.reply',
    slot: 'morning',
    value: 'ignore',
    label: 'Leave the message unanswered.',
    hint: 'Send nothing. Maya can notice the silence, not your reasons.',
    next: 'apartment.departure',
    response: [paragraph('You leave Maya’s message unanswered.')],
  },
  {
    id: 'promotion.professional',
    node: 'office.daniel',
    slot: 'promotion',
    value: 'professional',
    label: '“Priya earned it.”',
    hint: 'Keep the disappointment private.',
    next: 'office.benton',
    response: [
      speech(
        'Daniel',
        'Daniel nods. “Sure,” he says, in a tone that means he believes none of it.',
      ),
    ],
  },
  {
    id: 'promotion.angry',
    node: 'office.daniel',
    slot: 'promotion',
    value: 'angry',
    label: '“I wrote her last three strategic briefs.”',
    hint: 'Let Daniel see the anger.',
    next: 'office.benton',
    response: [
      speech(
        'Daniel',
        '“I know,” Daniel says. “That’s why I told you before Benton could call it development feedback.”',
      ),
    ],
  },
  {
    id: 'promotion.joke',
    node: 'office.daniel',
    slot: 'promotion',
    value: 'joke',
    label: '“Excellent. Competence remains safely contained.”',
    hint: 'Hide behind humour.',
    next: 'office.benton',
    response: [paragraph('Daniel almost laughs. Almost.')],
  },
  {
    id: 'promotion.quiet',
    node: 'office.daniel',
    slot: 'promotion',
    value: 'quiet',
    label: 'Say nothing.',
    hint: 'Let Daniel share the silence.',
    next: 'office.benton',
    response: [paragraph('Daniel lets the silence stand. That is one reason you trust him.')],
  },
  {
    id: 'benton.obey',
    node: 'office.benton',
    slot: 'benton',
    value: 'obey',
    label: '“You will have it before lunch.”',
    hint: 'Accept the narrow assignment.',
    next: 'office.departure',
    response: [
      speech(
        'Benton',
        'Benton gives one economical nod. “Good. You’ve always understood priorities.” He places the data slate on your desk and turns away.',
      ),
      thought(
        'I said yes before asking why he came in person. His approval still works on me more quickly than I care to admit.',
      ),
    ],
  },
  {
    id: 'benton.push',
    node: 'office.benton',
    slot: 'benton',
    value: 'push',
    label: '“Why is Strategic Intelligence reviewing a routine purchase?”',
    hint: 'Ask for the context Benton omitted.',
    next: 'office.departure',
    response: [
      speech(
        'Benton',
        'Benton studies you for half a second. “Executive Intelligence requested an independent review. Your job is the acquisition logic, not the request.” He sets down the slate without breaking eye contact.',
      ),
      thought(
        'He answered without answering. He has given me a source for the request, but no reason for it.',
      ),
    ],
  },
  {
    id: 'benton.promotion',
    node: 'office.benton',
    slot: 'benton',
    value: 'promotion',
    label: '“Before that, we should discuss the deputy director decision.”',
    hint: 'Make him acknowledge it.',
    next: 'office.departure',
    response: [
      speech(
        'Benton',
        'Benton’s expression settles into practiced sympathy. “Priya is the stronger fit for executive leadership. We can discuss your development path next quarter.” Then he places the Helix file directly over the promotion memorandum.',
      ),
      thought(
        'I do not regret forcing him to say it aloud. I regret giving him one more chance to be honest with me.',
      ),
    ],
  },
  {
    id: 'mayaPromotion.fine',
    node: 'maya.promotion',
    slot: 'mayaPromotion',
    value: 'fine',
    label: '“Priya earned it. I am fine.”',
    hint: 'Give Maya the professional answer.',
    next: 'maya.invitation',
    response: [
      speech(
        'Maya',
        '“Of course you are,” Maya says, giving you the look she reserves for transparent lies.',
      ),
    ],
  },
  {
    id: 'mayaPromotion.hurt',
    node: 'maya.promotion',
    slot: 'mayaPromotion',
    value: 'hurt',
    label: '“I thought this one was mine.”',
    hint: 'Admit that the decision hurt.',
    next: 'maya.invitation',
    response: [speech('Maya', 'Maya’s expression softens. “I know. It should’ve been yours.”')],
  },
  {
    id: 'mayaPromotion.angry',
    node: 'maya.promotion',
    slot: 'mayaPromotion',
    value: 'angry',
    label: '“They want my work, not my judgment.”',
    hint: 'Let her see the anger.',
    next: 'maya.invitation',
    response: [
      speech(
        'Maya',
        '“Then stop making it so easy for them to keep you where you are,” Maya says.',
      ),
    ],
  },
  {
    id: 'mayaPromotion.deflect',
    node: 'maya.promotion',
    slot: 'mayaPromotion',
    value: 'deflect',
    label: '“The coffee may save me.”',
    hint: 'Change the subject without fooling her.',
    next: 'maya.invitation',
    response: [speech('Maya', '“Coward,” Maya says, but she slides the coffee closer.')],
  },
  {
    id: 'invitation.yes',
    node: 'maya.invitation',
    slot: 'invitation',
    value: 'yes',
    label: '“Eight o’clock.”',
    hint: 'Make the plan real.',
    next: 'maya.case',
    response: [speech('Maya', '“Eight,” she says. “I am holding you to that.”')],
  },
  {
    id: 'invitation.maybe',
    node: 'maya.invitation',
    slot: 'invitation',
    value: 'maybe',
    label: '“If Benton releases me.”',
    hint: 'Let work decide again.',
    next: 'maya.case',
    response: [speech('Maya', '“I will assume that means yes until you disappoint me,” she says.')],
  },
  {
    id: 'invitation.no',
    node: 'maya.invitation',
    slot: 'invitation',
    value: 'no',
    label: '“Not tonight.”',
    hint: 'Decline the invitation without ending the conversation.',
    next: 'maya.case',
    response: [paragraph('Maya takes a breath, then lets the invitation rest.')],
  },
  {
    id: 'disclosure.voss',
    node: 'maya.case',
    slot: 'disclosure',
    value: 'voss',
    label: '“Dr Lena Voss is buried in the personnel records.”',
    hint: 'Share the restricted personnel connection. Maya will know what you found.',
    requires: 'voss_connection',
    next: 'maya.goodbye',
    response: [
      speech(
        'Maya',
        'Maya repeats the name once. “Voss works in Adaptive Medicine, not acquisitions. Send me nothing. I will look from my side.”',
      ),
    ],
  },
  {
    id: 'disclosure.contradiction',
    node: 'maya.case',
    slot: 'disclosure',
    value: 'contradiction',
    label: '“The patent rationale does not survive the financial record.”',
    hint: 'Share the analytical problem, without other case details.',
    requires: 'patent_conflict',
    next: 'maya.goodbye',
    response: [
      speech(
        'Maya',
        '“Then the rationale needs checking,” Maya says. “Be careful who you correct.”',
      ),
    ],
  },
  {
    id: 'disclosure.private',
    node: 'maya.case',
    slot: 'disclosure',
    value: 'private',
    label: '“Benton told me to keep it narrow.”',
    hint: 'Signal concern while protecting the details.',
    next: 'maya.goodbye',
    response: [speech('Maya', 'Maya studies you. “That was not an answer. It was a warning.”')],
  },
  {
    id: 'disclosure.nothing',
    node: 'maya.case',
    slot: 'disclosure',
    value: 'nothing',
    label: '“It is probably nothing.”',
    hint: 'Keep the findings private and bring the conversation to a close.',
    next: 'maya.goodbye',
    response: [speech('Maya', '“You are a terrible liar,” Maya says. She gathers her coffee.')],
  },
];
export const dialogue = ChoiceSchema.array().parse(raw);
export const choiceById = Object.fromEntries(dialogue.map((c) => [c.id, c]));
