import { z } from 'zod';
import { BlockSchema } from '../content/schema';
const optional = (values: [string, ...string[]]) => z.enum(values).nullable();
export const ClinicSchema = z
  .object({
    completed: z.array(z.string()).max(200),
    response: z.array(BlockSchema).max(20),
    morning: optional(['answer', 'miss', 'message', 'quiet']),
    privacy: optional(['stay', 'ask', 'demand', 'silent']),
    sloanePresent: z.boolean(),
    exam: optional(['terminal', 'equipment', 'scan', 'skip']),
    opportunity: z.number().int().min(0).max(1),
    profileDraft: optional(['existing', 'executive', 'socialite', 'operative']),
    profile: optional(['existing', 'executive', 'socialite', 'operative']),
    attention: optional(['face', 'body', 'technical', 'sloane', 'away']),
    displayed: optional(['hostility', 'indifference', 'curiosity', 'silent']),
    authorized: z.boolean(),
    stage: z.enum(['unchanged', 'voice', 'face', 'complete']),
    paused: z.boolean(),
    voice: optional(['lower', 'evelyn']),
    face: optional(['unfamiliar', 'temporary', 'beautiful', 'sloane']),
    mirror: optional(['me', 'notme', 'unknown', 'beautiful', 'anger', 'unnamed', 'skip']),
    outfitDraft: optional(['executive', 'socialite', 'shadow']),
    makeupDraft: optional(['corporate', 'minimal', 'evening', 'custom']),
    outfit: optional(['executive', 'socialite', 'shadow']),
    makeup: optional(['corporate', 'minimal', 'evening', 'custom']),
    belongings: z.enum(['carried', 'screening', 'locker', 'returned']),
    contact: optional(['brief', 'identity', 'quiet']),
    credentials: z.boolean(),
    earpiece: z.boolean(),
    investment: z.number().int().nonnegative(),
    vossTrust: z.number().int(),
    outcome: optional(['stopped', 'departed']),
  })
  .strict();
export const initialClinic = (): z.infer<typeof ClinicSchema> => ({
  completed: [],
  response: [],
  morning: null,
  privacy: null,
  sloanePresent: true,
  exam: null,
  opportunity: 1,
  profileDraft: null,
  profile: null,
  attention: null,
  displayed: null,
  authorized: false,
  stage: 'unchanged',
  paused: false,
  voice: null,
  face: null,
  mirror: null,
  outfitDraft: null,
  makeupDraft: null,
  outfit: null,
  makeup: null,
  belongings: 'carried',
  contact: null,
  credentials: false,
  earpiece: false,
  investment: 0,
  vossTrust: 0,
  outcome: null,
});
